routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/admin', 'Admin\GuardController@index')->name('panel.index');
Route::post('/check', 'Admin\GuardController@check')->name('login.check');

Route::group(['prefix' => 'admin-panel'], function () {
    Route::get('/dashboard', 'Admin\PanelController@index')->name('panel.welcome');

    Route::get('events/get', 'Admin\EventController@get')->name('events.get');
    Route::post('events/upload', 'Admin\EventController@upload')->name('events.upload');
    Route::post('events/delete', 'Admin\EventController@imageDelete')->name('event.image.delete');
    Route::resource('events', 'Admin\EventController');

    Route::post('faqs/sort', 'Admin\FaqController@sort')->name('faqs.sort');
    Route::resource('faqs', 'Admin\FaqController');

    Route::post('elements/sort', 'Admin\MenuElementController@sort')->name('elements.sort');
    Route::resource('menu.elements', 'Admin\MenuElementController');

    Route::resource('menus', 'Admin\MenuController');

    Route::resource('pages', 'Admin\PageController');

    Route::post('sections/sort', 'Admin\PageSectionController@sort')->name('sections.sort');
    Route::resource('page.sections', 'Admin\PageSectionController');

    Route::get('product-categories/get', 'Admin\CategoryController@get')->name('product-categories.get');
    Route::resource('product-categories', 'Admin\CategoryController');

    Route::post('products/sort', 'Admin\ProductController@sort')->name('products.sort');
    Route::get('products/get', 'Admin\ProductController@get')->name('products.get');
    Route::resource('products', 'Admin\ProductController');

    Route::get('recipes/get', 'Admin\RecipeController@get')->name('recipes.get');
    Route::resource('recipes', 'Admin\RecipeController');

    Route::resource('site-settings', 'Admin\SettingController');

    Route::post('slides/sort', 'Admin\SliderController@sort')->name('slides.sort');
    Route::resource('slides', 'Admin\SliderController');

    Route::resource('users', 'Admin\UserController');

    Route::get('/clear-cache', 'Admin\AdminBaseController@clearCache')->name('panel.clear.cache');

    Route::get('/logout', 'Admin\GuardController@logout')->name('panel.logout');
});


//Route::group(['middleware' => 'page-cache'], function () {

    Route::get('/sss', 'Site\PageController@faqs')
        ->name('sss');

    Route::get('/iletisim', 'Site\PageController@contact')
        ->name('contact');

//products
    Route::get('/etkinlikler', 'Site\EventController@events')
        ->name('events');

//product
    Route::get('/etkinlik/{slug}', 'Site\EventController@event')
        ->where('slug', '([A-Za-z0-9\-\/]+)')
        ->name('event');

//products
    Route::get('/urunler/{slug}', 'Site\ProductController@products')
        ->where('slug', '([A-Za-z0-9\-\/]+)')
        ->name('products');

//product
    Route::get('/urun/{category}/{slug}', 'Site\ProductController@product')
        ->where('category', '([A-Za-z0-9\-\/]+)')
        ->where('slug', '([A-Za-z0-9\-\/]+)')
        ->name('product');

//recipes
    Route::get('/tarifler', 'Site\RecipeController@recipes')
        ->where('slug', '([A-Za-z0-9\-\/]+)')
        ->name('recipes');

//recipe
    Route::get('/tarif/{slug}', 'Site\RecipeController@recipe')
        ->where('slug', '([A-Za-z0-9\-\/]+)')
        ->name('recipe');

//pages
    Route::get('{slug}', 'Site\PageController@page')
        ->where('slug', '([A-Za-z0-9\-\/]+)')
        ->name('page');

//home
    Route::get('/', [
        'as'   => 'home',
        'uses' => 'Site\PageController@index'
    ]);
//});

app/Http/Controllers/Admin/CategoryController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Models\ProductCategory;
use Illuminate\Http\Request;
use Intervention\Image\Facades\Image;

class CategoryController extends AdminBaseController
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('admin.content.categories.list');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $parent_categories = ProductCategory::where('parent_id', 0)->get()->pluck('name', 'id');
        $parent_categories->prepend('ANA KATEGORİ', 0);
        return view('admin.content.categories.create', compact('parent_categories'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     * @throws \HttpException
     * @throws \Illuminate\Contracts\Filesystem\FileNotFoundException
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'image'  => 'nullable|image|mimes:jpeg,jpg,png',
            'name'   => 'required|max:255',
            'active' => 'required'
        ]);

        $parent = ProductCategory::find($request->parent_id);

        if ($request->file('image') !== null) {

            $file = $request->file('image');
            $name = str_slug($request->input('name')) . '.' . $file->getClientOriginalExtension();

            if (!\Storage::disk('uploads')->put('urunler' . DIRECTORY_SEPARATOR . $parent->slug . DIRECTORY_SEPARATOR . $name, \File::get($file))) {
                throw new \HttpException(500);
            }

            $targetDir = public_path('uploads/urunler' . DIRECTORY_SEPARATOR . $parent->slug);
            $path      = $targetDir . DIRECTORY_SEPARATOR . $name;

            $img = Image::make($path);

            //thumbnail
            $img->fit(getenv('IMAGE_THUMB'))->save($path, 80);

        }

        $category = new ProductCategory();

        $category->parent_id   = $request->parent_id;
        $category->name        = $request->name;
        $category->slug        = str_slug($category->name);
        $category->description = $request->description;
        $category->image       = isset($name) ? 'uploads/urunler' . DIRECTORY_SEPARATOR . $parent->slug . DIRECTORY_SEPARATOR . $name : null;
        $category->active      = $request->active;
        $category->deletable   = 1;

        $category->save();

        \Session::flash('success', 'İşleminiz gerçekleştirildi');

        return redirect()->route('product-categories.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $category = ProductCategory::find($id);

        if ($category === null) {
            \Session::flash('error', 'Kayıt bulunamadı');
            return redirect()->route('product-categories.index');
        }

        $parent_categories = ProductCategory::where('parent_id', 0)->get()->pluck('name', 'id');
        $parent_categories->prepend('ANA KATEGORİ', 0);

        return view('admin.content.categories.edit', compact('category', 'parent_categories'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @param  int $id
     * @return \Illuminate\Http\Response
     * @throws \HttpException
     * @throws \Illuminate\Contracts\Filesystem\FileNotFoundException
     */
    public function update(Request $request, $id)
    {
        $this->validate($request, [
            'image'  => 'nullable|image|mimes:jpeg,jpg,png',
            'name'   => 'required|max:255',
            'active' => 'required'
        ]);

        $parent = ProductCategory::find($request->parent_id);

        if ($request->file('image') !== null) {

            $file = $request->file('image');
            $name = str_slug($request->input('name')) . '.' . $file->getClientOriginalExtension();

            if (!\Storage::disk('uploads')->put('urunler' . DIRECTORY_SEPARATOR . $parent->slug . DIRECTORY_SEPARATOR . $name, \File::get($file))) {
                throw new \HttpException(500);
            }

            $targetDir = public_path('uploads/urunler' . DIRECTORY_SEPARATOR . $parent->slug);
            $path      = $targetDir . DIRECTORY_SEPARATOR . 'thumb_' . $name;

            $img = Image::make($path);

            //thumbnail
            $img->fit(300)->save($path, 80);

        }

        $category = ProductCategory::find($id);

        $category->parent_id   = $request->parent_id;
        $category->name        = $request->name;
        $category->slug        = str_slug($category->name);
        $category->description = $request->description;
        $category->image       = isset($name) ? 'uploads/urunler' . DIRECTORY_SEPARATOR . $parent->slug . DIRECTORY_SEPARATOR . $name : null;
        $category->active      = $request->active;
        $category->deletable   = 1;

        $category->save();

        \Session::flash('success', 'İşleminiz gerçekleştirildi');

        return redirect()->route('product-categories.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $event = ProductCategory::find($id);

        if ($event === null) {
            \Session::flash('error', 'Kayıt bulunamadı');
            return ['status' => false];
        }

        $event->delete();

        \Session::flash('success', 'İşleminiz gerçekleştirildi');

        return ['status' => true];
    }

    public function get()
    {
        $data = ProductCategory::with('parent_category_listing')->orderBy('parent_id', 'asc')->get();

        return ['data' => $data];
    }
}

resources/views/admin/content/categories/create.blade.php
@extends('admin.layouts.main')
@section('content')
    <!-- BEGIN: Subheader -->
    @include('admin.parts.breadcrumb',['page'=> 'Ürün Kategorileri'])
    <div class="m-content">
        <!--Begin::Section-->
        <div class="row">
            <div class="col-lg-12">
                <!--begin::Portlet-->
                <div class="m-portlet">
                    <div class="m-portlet__head">
                        <div class="m-portlet__head-caption">
                            <div class="m-portlet__head-title">
												<span class="m-portlet__head-icon m--hide">
													<i class="la la-gear"></i>
												</span>
                                <h3 class="m-portlet__head-text">
                                    Ürün Kategorisi Bilgiler
                                </h3>
                            </div>
                        </div>
                    </div>
                    {!! Form::open(['route' => 'product-categories.store', 'class'=>'m-form']) !!}
                    <div class="m-portlet__body">
                        @if ($errors->any())
                            <div class="alert alert-danger">
                                <ul>
                                    @foreach ($errors->all() as $error)
                                        <li>{{ $error }}</li>
                                    @endforeach
                                </ul>
                            </div>
                        @endif
                        <div class="form-group m-form__group col-lg-9">
                            {!! Form::label('image', 'Görsel :'); !!}
                            {!! Form::file('image'); !!}
                        </div>

                        <div class="form-group m-form__group col-lg-4">
                            {!! Form::label('parent_id', 'Kategori :'); !!}
                            {!! Form::select('parent_id', $parent_categories ,null, ['class' => 'form-control m-input']); !!}
                        </div>
                        <div class="form-group m-form__group col-lg-4">
                            {!! Form::label('name', 'Kategori Adı :'); !!}
                            {!! Form::text('name', null, ['class' => 'form-control m-input']); !!}
                        </div>

                        <div class="form-group m-form__group col-lg-6">
                            {!! Form::label('description', 'Açıklama :'); !!}
                            {!! Form::textarea('description',null, ['class' => 'form-control m-input']); !!}
                        </div>

                        <div class="form-group m-form__group col-lg-4">
                            {!! Form::label('active', 'Durum :'); !!}
                            {!! Form::select('active', ['0' => 'Pasif', '1' => 'Aktif'],null, ['class' => 'form-control m-input']); !!}
                        </div>
                    </div>
                    <div class="m-portlet__foot m-portlet__foot--fit">
                        <div class="m-form__actions m-form__actions">
                            <button class="btn btn-primary">
                                {!! Form::submit('Kaydet', ['class'=>'btn btn-primary']) !!}
                            </button>
                        </div>
                    </div>
                    {!! Form::close() !!}
                </div>
                <!--end::Portlet-->
            </div>
        </div>
        <!--End::Section-->
    </div>
@endsection

resources/views/admin/content/categories/edit.blade.php
@extends('admin.layouts.main')
@section('content')
    <!-- BEGIN: Subheader -->
    @include('admin.parts.breadcrumb',['page'=> 'Ürün Kategorileri'])
    <div class="m-content">
        <!--Begin::Section-->
        <div class="row">
            <div class="col-lg-12">
                <!--begin::Portlet-->
                <div class="m-portlet">
                    <div class="m-portlet__head">
                        <div class="m-portlet__head-caption">
                            <div class="m-portlet__head-title">
												<span class="m-portlet__head-icon m--hide">
													<i class="la la-gear"></i>
												</span>
                                <h3 class="m-portlet__head-text">
                                    Ürün Kategorisi Bilgiler
                                </h3>
                            </div>
                        </div>
                    </div>
                    {!! Form::model($category,['route' => ['product-categories.update', $category->id], 'class'=>'m-form', 'method'=>'PUT']) !!}
                    <div class="m-portlet__body">
                        @if ($errors->any())
                            <div class="alert alert-danger">
                                <ul>
                                    @foreach ($errors->all() as $error)
                                        <li>{{ $error }}</li>
                                    @endforeach
                                </ul>
                            </div>
                        @endif
                        <div class="form-group m-form__group col-lg-9">
                            {!! Form::label('image', 'Görsel :'); !!}
                            @if($category->image)
                                <div class="form-group m-form__group col-lg-9" style="padding-left: 0 !important;">
                                    <img src="{{$category->image}}" alt="{{$category->name}}" style="width: 200px"/>
                                </div>
                            @endif
                            {!! Form::file('image'); !!}
                        </div>

                        <div class="form-group m-form__group col-lg-4">
                            {!! Form::label('parent_id', 'Kategori :'); !!}
                            {!! Form::select('parent_id', $parent_categories ,null, ['class' => 'form-control m-input']); !!}
                        </div>
                        <div class="form-group m-form__group col-lg-4">
                            {!! Form::label('name', 'Kategori Adı :'); !!}
                            {!! Form::text('name', null, ['class' => 'form-control m-input']); !!}
                        </div>

                        <div class="form-group m-form__group col-lg-6">
                            {!! Form::label('description', 'Açıklama :'); !!}
                            {!! Form::textarea('description',null, ['class' => 'form-control m-input']); !!}
                        </div>

                        <div class="form-group m-form__group col-lg-4">
                            {!! Form::label('active', 'Durum :'); !!}
                            {!! Form::select('active', ['0' => 'Pasif', '1' => 'Aktif'],null, ['class' => 'form-control m-input']); !!}
                        </div>
                    </div>
                    <div class="m-portlet__foot m-portlet__foot--fit">
                        <div class="m-form__actions m-form__actions">
                            <button class="btn btn-primary">
                                {!! Form::submit('Kaydet', ['class'=>'btn btn-primary']) !!}
                            </button>
                        </div>
                    </div>
                    {!! Form::close() !!}
                </div>
                <!--end::Portlet-->
            </div>
        </div>
        <!--End::Section-->
    </div>
@endsection

resources/views/admin/content/categories/list.blade.php
@extends('admin.layouts.main')
@section('content')
    @include('admin.parts.breadcrumb',['page'=> 'Ürün Kategorileri'])
    <div class="m-content">
        <div class="m-portlet m-portlet--mobile">
            <div class="m-portlet__head">
                <div class="m-portlet__head-caption">
                    <div class="m-portlet__head-title">
                        <h3 class="m-portlet__head-text">
                            Liste
                        </h3>
                    </div>
                </div>
            </div>
            <div class="m-portlet__body">
                <!--begin: Search Form -->
                <div class="m-form m-form--label-align-right m--margin-top-20 m--margin-bottom-30">
                    <div class="row align-items-center">
                        <div class="col-xl-8 order-2 order-xl-1">
                            <div class="form-group m-form__group row align-items-center">
                                <div class="col-md-8">
                                    <div class="m-input-icon m-input-icon--left">
                                        <input type="text" class="form-control m-input" placeholder="Ara..."
                                               id="generalSearch">
                                        <span class="m-input-icon__icon m-input-icon__icon--left">
                                            <span>
                                                <i class="la la-search"></i>
                                            </span>
                                        </span>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-xl-4 order-1 order-xl-2 m--align-right">
                            <a href="{{route('product-categories.create')}}"
                               class="btn btn-primary m-btn m-btn--custom m-btn--icon m-btn--air m-btn--pill">
												<span>
													<i class="la la-plus-circle"></i>
													<span>
														Yeni Kategori
													</span>
												</span>
                            </a>
                            <div class="m-separator m-separator--dashed d-xl-none"></div>
                        </div>
                    </div>
                </div>
                <!--end: Search Form -->
                <!--begin: Datatable -->
                <div class="m_datatable" id="ajax_data"></div>
                <!--end: Datatable -->
            </div>
        </div>
    </div>
@endsection

@section('page_js')
    <script>

        $(function () {
            $('body').on('click', 'a.del', function (e) {
                e.preventDefault();
                var id = $(this).data('id');

                swal({
                    title: "Uyarı!",
                    text: "Silmek istediğinize emin misiniz?",
                    type: "warning",
                    showCancelButton: true,
                    confirmButtonColor: 'btn btn-danger',
                    confirmButtonText: "Evet",
                    cancelButtonText: "İptal"
                }).then(function(result) {
                    if (result.value) {
                        $.ajax({
                            url: '{{route('product-categories.index')}}/' + id,
                            dataType: "json",
                            type: 'DELETE',
                            success: function (result) {
                                // Do something with the result
                                if(result.status)
                                    location.reload();
                            }
                        });
                    }
                });
            });
        });

        var dtra = function () {
            //== Private functions

            var data = function () {

                var datatable = $('.m_datatable').mDatatable({
                    // datasource definition
                    data: {
                        type: 'remote',
                        source: {
                            read: {
                                // sample GET method
                                method: 'GET',
                                //url: 'https://keenthemes.com/metronic/preview/inc/api/datatables/demos/default.php',
                                url: '{{route('product-categories.get')}}',
                                map: function (raw) {
                                    // sample data mapping
                                    var dataSet = raw;
                                    if (typeof raw.data !== 'undefined') {
                                        dataSet = raw.data;
                                    }
                                    return dataSet;
                                },
                            },
                        },
                        serverPaging: false,
                        serverFiltering: false,
                        serverSorting: false,
                    },

                    translate: {
                        records: {
                            processing: 'Yükleniyor...',
                            noRecords: 'Kayıt bulunamadı',
                        },
                        toolbar: {
                            pagination: {
                                items: {
                                    default: {
                                        first: 'İlk',
                                        prev: 'Önceki',
                                        next: 'Sonraki',
                                        last: 'Son',
                                        more: 'Daha fazla',
                                        input: 'Sayfa no',
                                        select: 'Sayfalama',
                                    },
                                    @verbatim
                                    info: '{{total}} kayıttan {{start}} - {{end}} arasındaki kayıtlar gösteriliyor',
                                    @endverbatim
                                },
                            },
                        },
                    },

                    // layout definition
                    layout: {
                        scroll: false,
                        footer: false
                    },

                    // column sorting
                    sortable: false,

                    pagination: true,

                    search: {
                        input: $('#generalSearch'),
                    },

                    // columns definition
                    columns: [
                        {
                            field: 'name',
                            title: 'Kategori Adı',
                            width: 300,
                            sortable: false,
                            // basic templating support for column rendering,
                        }, {
                            field: 'parent_category_listing.name',
                            title: 'Ana Kategori',
                        }, {
                            field: 'active',
                            title: 'Durum',
                            // callback function support for column rendering
                            template: function (row) {
                                var status = {
                                    0: {'title': 'Pasif', 'class': 'm-badge--danger'},
                                    1: {'title': 'Aktif', 'class': ' m-badge--success'},
                                };
                                return '<span class="m-badge ' + status[row.active].class + ' m-badge--wide">' + status[row.active].title + '</span>';
                            },
                        }, {
                            field: 'Actions',
                            title: 'İşlemler',
                            sortable: false,
                            overflow: 'visible',
                            template: function (row, index, datatable) {
                                if(row.deletable === 0){
                                    return '\
                                    <a href="{{route('product-categories.index')}}/' + row.id + '/edit" class="m-portlet__nav-link btn m-btn m-btn--hover-accent m-btn--icon m-btn--icon-only m-btn--pill" title="Düzenle">\
                                        <i class="la la-edit"></i>\
                                    </a>\
                                    ';
                                }else {
                                    return '\
                                    <a href="{{route('product-categories.index')}}/' + row.id + '/edit" class="m-portlet__nav-link btn m-btn m-btn--hover-accent m-btn--icon m-btn--icon-only m-btn--pill" title="Düzenle">\
                                        <i class="la la-edit"></i>\
                                    </a>\
                                    <a href="#" data-id="' + row.id + '" class="m-portlet__nav-link btn m-btn m-btn--hover-danger m-btn--icon m-btn--icon-only m-btn--pill del" title="Sil">\
                                        <i class="la la-trash"></i>\
                                    </a>\
                                ';
                                }
                            },
                        }],
                });

                var query = datatable.getDataSourceQuery();

            };

            return {
                // public functions
                init: function () {
                    data();
                },
            };
        }();

        jQuery(document).ready(function () {
            dtra.init();
        });
    </script>
@endsection