routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/admin', 'Admin\GuardController@index')->name('panel.index');
Route::post('/check', 'Admin\GuardController@check')->name('login.check');

Route::group(['prefix' => 'admin-panel'], function () {
    Route::get('/dashboard', 'Admin\PanelController@index')->name('panel.welcome');

    Route::get('events/get', 'Admin\EventController@get')->name('events.get');
    Route::post('events/upload', 'Admin\EventController@upload')->name('events.upload');
    Route::post('events/delete', 'Admin\EventController@imageDelete')->name('event.image.delete');
    Route::resource('events', 'Admin\EventController');

    Route::post('faqs/sort', 'Admin\FaqController@sort')->name('faqs.sort');
    Route::resource('faqs', 'Admin\FaqController');

    Route::post('elements/sort', 'Admin\MenuElementController@sort')->name('elements.sort');
    Route::resource('menu.elements', 'Admin\MenuElementController');

    Route::resource('menus', 'Admin\MenuController');

    Route::resource('pages', 'Admin\PageController');

    Route::post('sections/sort', 'Admin\PageSectionController@sort')->name('sections.sort');
    Route::resource('page.sections', 'Admin\PageSectionController');

    Route::get('product-categories/get', 'Admin\CategoryController@get')->name('product-categories.get');
    Route::resource('product-categories', 'Admin\CategoryController');

    Route::post('products/sort', 'Admin\ProductController@sort')->name('products.sort');
    Route::get('products/get', 'Admin\ProductController@get')->name('products.get');
    Route::resource('products', 'Admin\ProductController');

    Route::get('recipes/get', 'Admin\RecipeController@get')->name('recipes.get');
    Route::resource('recipes', 'Admin\RecipeController');

    Route::resource('site-settings', 'Admin\SettingController');

    Route::post('slides/sort', 'Admin\SliderController@sort')->name('slides.sort');
    Route::resource('slides', 'Admin\SliderController');

    Route::resource('users', 'Admin\UserController');

    Route::get('/clear-cache', 'Admin\AdminBaseController@clearCache')->name('panel.clear.cache');

    Route::get('/logout', 'Admin\GuardController@logout')->name('panel.logout');
});


//Route::group(['middleware' => 'page-cache'], function () {

    Route::get('/sss', 'Site\PageController@faqs')
        ->name('sss');

    Route::get('/iletisim', 'Site\PageController@contact')
        ->name('contact');

//products
    Route::get('/etkinlikler', 'Site\EventController@events')
        ->name('events');

//product
    Route::get('/etkinlik/{slug}', 'Site\EventController@event')
        ->where('slug', '([A-Za-z0-9\-\/]+)')
        ->name('event');

//products
    Route::get('/urunler/{slug}', 'Site\ProductController@products')
        ->where('slug', '([A-Za-z0-9\-\/]+)')
        ->name('products');

//product
    Route::get('/urun/{category}/{slug}', 'Site\ProductController@product')
        ->where('category', '([A-Za-z0-9\-\/]+)')
        ->where('slug', '([A-Za-z0-9\-\/]+)')
        ->name('product');

//recipes
    Route::get('/tarifler', 'Site\RecipeController@recipes')
        ->where('slug', '([A-Za-z0-9\-\/]+)')
        ->name('recipes');

//recipe
    Route::get('/tarif/{slug}', 'Site\RecipeController@recipe')
        ->where('slug', '([A-Za-z0-9\-\/]+)')
        ->name('recipe');

//pages
    Route::get('{slug}', 'Site\PageController@page')
        ->where('slug', '([A-Za-z0-9\-\/]+)')
        ->name('page');

//home
    Route::get('/', [
        'as'   => 'home',
        'uses' => 'Site\PageController@index'
    ]);
//});

app/Models/Slide.php
<?php

/**
 * Created by Reliese Model.
 * Date: Thu, 12 Apr 2018 13:04:53 +0000.
 */

namespace App\Models;

use Reliese\Database\Eloquent\Model as Eloquent;

/**
 * Class Slide
 * 
 * @property int $id
 * @property string $image
 * @property string $top_text
 * @property string $middle_text
 * @property string $description
 * @property string $route
 * @property int $order
 * @property int $active
 *
 * @package App\Models
 */
class Slide extends Eloquent
{
	public $timestamps = false;

	protected $casts = [
		'order' => 'int',
		'active' => 'int'
	];

	protected $fillable = [
		'image',
		'top_text',
		'middle_text',
		'description',
		'route',
		'order',
		'active'
	];
}

resources/views/admin/content/slide/create.blade.php
@extends('admin.layouts.main')
@section('content')
    <!-- BEGIN: Subheader -->
    @include('admin.parts.breadcrumb',['page'=> 'Slides'])
    <div class="m-content">
        <!--Begin::Section-->
        <div class="row">
            <div class="col-lg-12">
                <!--begin::Portlet-->
                <div class="m-portlet">
                    <div class="m-portlet__head">
                        <div class="m-portlet__head-caption">
                            <div class="m-portlet__head-title">
												<span class="m-portlet__head-icon m--hide">
													<i class="la la-gear"></i>
												</span>
                                <h3 class="m-portlet__head-text">
                                    Slide Bilgiler
                                </h3>
                            </div>
                        </div>
                    </div>
                    {!! Form::open(['route' => 'slides.store', 'class'=>'m-form', 'files' => true]) !!}
                    <div class="m-portlet__body">
                        @if ($errors->any())
                            <div class="alert alert-danger">
                                <ul>
                                    @foreach ($errors->all() as $error)
                                        <li>{{ $error }}</li>
                                    @endforeach
                                </ul>
                            </div>
                        @endif
                        <div class="form-group m-form__group col-lg-9">
                            {!! Form::label('image', 'Görsel :'); !!}
                            {!! Form::file('image'); !!}
                        </div>

                        <div class="form-group m-form__group col-lg-9">
                            {!! Form::label('route', 'Hedef Route (Rota - Slug) :'); !!}
                            {!! Form::text('route', null, ['class' => 'form-control m-input']); !!}
                        </div>

                        <div class="form-group m-form__group col-lg-9">
                            {!! Form::label('top_text', 'Header Üst Yazı :'); !!}
                            {!! Form::textarea('top_text',null, ['class' => 'form-control m-input']); !!}
                        </div>
                        <div class="form-group m-form__group col-lg-9">
                            {!! Form::label('middle_text', 'Header Orta Yazı :'); !!}
                            {!! Form::textarea('middle_text',null, ['class' => 'form-control m-input']); !!}
                        </div>
                        <div class="form-group m-form__group col-lg-9">
                            {!! Form::label('description', 'Header Alt Yazı :'); !!}
                            {!! Form::textarea('description',null, ['class' => 'form-control m-input']); !!}
                        </div>
                        <div class="form-group m-form__group col-lg-3">
                            {!! Form::label('active', 'Durum :'); !!}
                            {!! Form::select('active', ['0' => 'Pasif', '1' => 'Aktif'],null, ['class' => 'form-control m-input']); !!}
                        </div>
                    </div>
                    <div class="m-portlet__foot m-portlet__foot--fit">
                        <div class="m-form__actions m-form__actions">
                            <button class="btn btn-primary">
                                {!! Form::submit('Kaydet', ['class'=>'btn btn-primary']) !!}
                            </button>
                        </div>
                    </div>
                    {!! Form::close() !!}
                </div>
                <!--end::Portlet-->
            </div>
        </div>
        <!--End::Section-->
    </div>
@endsection
@section('page_js')
    <!--begin::Page Resources -->
    <script src="{{asset('assets/admin/assets/demo/default/custom/components/forms/widgets/summernote.js')}}"
            type="text/javascript"></script>
    <!--end::Page Resources -->
@endsection

resources/views/admin/content/slide/edit.blade.php
@extends('admin.layouts.main')
@section('content')
    <!-- BEGIN: Subheader -->
    @include('admin.parts.breadcrumb',['page'=> 'Slides'])
    <div class="m-content">
        <!--Begin::Section-->
        <div class="row">
            <div class="col-lg-12">
                <!--begin::Portlet-->
                <div class="m-portlet">
                    <div class="m-portlet__head">
                        <div class="m-portlet__head-caption">
                            <div class="m-portlet__head-title">
												<span class="m-portlet__head-icon m--hide">
													<i class="la la-info"></i>
												</span>
                                <h3 class="m-portlet__head-text">
                                    Slide Bilgiler
                                </h3>
                            </div>
                        </div>
                    </div>
                    {!! Form::model($slide,['route' => ['slides.update', $slide->id], 'class'=>'m-form', 'method'=>'PUT', 'files' => true]) !!}
                    <div class="m-portlet__body">
                        @if ($errors->any())
                            <div class="alert alert-danger">
                                <ul>
                                    @foreach ($errors->all() as $error)
                                        <li>{{ $error }}</li>
                                    @endforeach
                                </ul>
                            </div>
                        @endif
                        <div class="form-group m-form__group col-lg-9">
                            {!! Form::label('image', 'Görsel :'); !!}
                            @if($slide->image)
                                <div class="form-group m-form__group col-lg-9" style="padding-left: 0 !important;">
                                    <img src="{{$slide->image}}" alt="" style="width: 600px"/>
                                </div>
                            @endif
                            {!! Form::file('image'); !!}
                        </div>

                        <div class="form-group m-form__group col-lg-9">
                            {!! Form::label('route', 'Hedef Route (Rota - Slug) :'); !!}
                            {!! Form::text('route', null, ['class' => 'form-control m-input']); !!}
                        </div>

                        <div class="form-group m-form__group col-lg-9">
                            {!! Form::label('top_text', 'Header Üst Yazı :'); !!}
                            {!! Form::textarea('top_text',null, ['class' => 'form-control m-input']); !!}
                        </div>
                        <div class="form-group m-form__group col-lg-9">
                            {!! Form::label('middle_text', 'Header Orta Yazı :'); !!}
                            {!! Form::textarea('middle_text',null, ['class' => 'form-control m-input']); !!}
                        </div>
                        <div class="form-group m-form__group col-lg-9">
                            {!! Form::label('description', 'Header Alt Yazı :'); !!}
                            {!! Form::textarea('description',null, ['class' => 'form-control m-input']); !!}
                        </div>
                        <div class="form-group m-form__group col-lg-3">
                            {!! Form::label('active', 'Durum :'); !!}
                            {!! Form::select('active', ['0' => 'Pasif', '1' => 'Aktif'],null, ['class' => 'form-control m-input']); !!}
                        </div>
                    </div>
                    <div class="m-portlet__foot m-portlet__foot--fit">
                        <div class="m-form__actions m-form__actions">
                            <button class="btn btn-primary">
                                {!! Form::submit('Kaydet', ['class'=>'btn btn-primary']) !!}
                            </button>
                        </div>
                    </div>
                    {!! Form::close() !!}
                </div>
                <!--end::Portlet-->
            </div>
        </div>
        <!--End::Section-->
    </div>
@endsection

resources/views/admin/content/slide/list.blade.php
@extends('admin.layouts.main')
@section('content')
    @include('admin.parts.breadcrumb',['page'=> 'Slides'])
    <div class="m-content">
        <div class="m-portlet m-portlet--mobile">
            <div class="m-portlet__head">
                <div class="m-portlet__head-caption">
                    <div class="m-portlet__head-title">
                        <h3 class="m-portlet__head-text">
                            Liste
                        </h3>
                    </div>
                </div>
            </div>
            <div class="m-portlet__body">
                <!--begin: Search Form -->
                <div class="m-form m-form--label-align-right m--margin-top-20 m--margin-bottom-30">
                    <div class="row align-items-center">
                        <div class="col-lg-8">
                            <div class="m-alert m-alert--icon m-alert--outline alert alert-primary" role="alert">
                                <div class="m-alert__icon">
                                    <i class="la la-info-circle"></i>
                                </div>
                                <div class="m-alert__text">
                                    Sürükle bırak ile sıralamayı değiştirebilirsiniz.
                                </div>
                            </div>
                        </div>
                        <div class="col-lg-4 m--align-right">
                            <a href="{{route('slides.create')}}"
                               class="btn btn-primary m-btn m-btn--custom m-btn--icon m-btn--air m-btn--pill">
												<span>
													<i class="la la-plus-circle"></i>
													<span>
														Yeni Slide
													</span>
												</span>
                            </a>
                            <div class="m-separator m-separator--dashed d-xl-none"></div>
                        </div>
                    </div>
                </div>

                <div class="row" id="m_sortable_portlets">
                    <div class="col-lg-12">
                        @foreach($slides as $slide)
                            <div class="m-portlet m-portlet--mobile m-portlet--sortable" id="item-{{$slide->id}}">
                                <div class="m-portlet__head">
                                    <div class="m-portlet__head-caption">
                                        <div class="m-portlet__head-title">
                                            <h3 class="m-portlet__head-text">
                                                <img src="{{$slide->image}}" style="width: 350px"/>
                                                {{$slide->top_text}}
                                                @if($slide->active === 1)
                                                    <span class="m-badge  m-badge--success m-badge--wide">Aktif</span>
                                                @else
                                                    <span class="m-badge  m-badge--danger m-badge--wide">Pasif</span>
                                                @endif
                                            </h3>
                                        </div>
                                    </div>
                                    <div class="m-portlet__head-tools">
                                        <ul class="m-portlet__nav">
                                            <li class="m-portlet__nav-item">
                                                <a href="{{route('slides.edit', ['id'=>$slide->id])}}"
                                                   class="m-portlet__nav-link btn btn-secondary m-btn m-btn--icon m-btn--icon-only m-btn--pill">
                                                    <i class="la la-edit"></i>
                                                </a>
                                            </li>
                                            <li class="m-portlet__nav-item">
                                                <a href="#" data-id="{{$slide->id}}"
                                                   class="m-portlet__nav-link btn btn-secondary m-btn m-btn--icon m-btn--icon-only m-btn--pill del">
                                                    <i class="la la-trash"></i>
                                                </a>
                                            </li>
                                        </ul>
                                    </div>
                                </div>
                            </div>
                        @endforeach
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

@section('page_js')
    <!--begin::Page Vendors -->
    <script src="{{asset('assets/admin/assets/vendors/custom/jquery-ui/jquery-ui.bundle.js')}}" type="text/javascript"></script>
    <!--end::Page Vendors -->
    <script>

        $(function () {
            $('body').on('click', 'a.del', function (e) {
                e.preventDefault();
                var id = $(this).data('id');

                swal({
                    title: "Uyarı!",
                    text: "Silmek istediğinize emin misiniz?",
                    type: "warning",
                    showCancelButton: true,
                    confirmButtonColor: 'btn btn-danger',
                    confirmButtonText: "Evet",
                    cancelButtonText: "İptal"
                }).then(function (result) {
                    if (result.value) {
                        $.ajax({
                            url: '{{route('slides.index')}}/' + id,
                            dataType: "json",
                            type: 'DELETE',
                            success: function (result) {
                                if (result.status)
                                    location.reload();
                            }
                        });
                    }
                });
            });

            $("#m_sortable_portlets").sortable({
                connectWith: ".m-portlet__head",
                items: ".m-portlet",
                opacity: 0.8,
                handle : '.m-portlet__head',
                coneHelperSize: true,
                placeholder: 'm-portlet--sortable-placeholder',
                forcePlaceholderSize: true,
                tolerance: "pointer",
                helper: "clone",
                cancel: ".m-portlet--sortable-empty", // cancel dragging if portlet is in fullscreen mode
                revert: 250, // animation in milliseconds
                update: function(b, c) {
                    if (c.item.prev().hasClass("m-portlet--sortable-empty")) {
                        c.item.prev().before(c.item);
                    }

                    var data = $('#m_sortable_portlets').sortable('serialize');
                    console.log(data);

                    $.ajax({
                        data: data,
                        dataType: "json",
                        type: 'POST',
                        url: '{{ route('slides.sort') }}',
                        success:function (result) {
                            if (result.status){
                                swal({
                                    title: 'Bilgi',
                                    text: 'İşleminiz gerçekleştirildi',
                                    timer: 2000,
                                    type: 'success',
                                    showConfirmButton: false
                                });
                            }

                        }
                    });
                }
            });

        });
    </script>
@endsection