routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/admin', 'Admin\GuardController@index')->name('panel.index');
Route::post('/check', 'Admin\GuardController@check')->name('login.check');

Route::group(['prefix' => 'admin-panel'], function () {
    Route::get('/dashboard', 'Admin\PanelController@index')->name('panel.welcome');

    Route::get('events/get', 'Admin\EventController@get')->name('events.get');
    Route::post('events/upload', 'Admin\EventController@upload')->name('events.upload');
    Route::post('events/delete', 'Admin\EventController@imageDelete')->name('event.image.delete');
    Route::resource('events', 'Admin\EventController');

    Route::post('faqs/sort', 'Admin\FaqController@sort')->name('faqs.sort');
    Route::resource('faqs', 'Admin\FaqController');

    Route::post('elements/sort', 'Admin\MenuElementController@sort')->name('elements.sort');
    Route::resource('menu.elements', 'Admin\MenuElementController');

    Route::resource('menus', 'Admin\MenuController');

    Route::resource('pages', 'Admin\PageController');

    Route::post('sections/sort', 'Admin\PageSectionController@sort')->name('sections.sort');
    Route::resource('page.sections', 'Admin\PageSectionController');

    Route::get('product-categories/get', 'Admin\CategoryController@get')->name('product-categories.get');
    Route::resource('product-categories', 'Admin\CategoryController');

    Route::post('products/sort', 'Admin\ProductController@sort')->name('products.sort');
    Route::get('products/get', 'Admin\ProductController@get')->name('products.get');
    Route::resource('products', 'Admin\ProductController');

    Route::get('recipes/get', 'Admin\RecipeController@get')->name('recipes.get');
    Route::resource('recipes', 'Admin\RecipeController');

    Route::resource('site-settings', 'Admin\SettingController');

    Route::post('slides/sort', 'Admin\SliderController@sort')->name('slides.sort');
    Route::resource('slides', 'Admin\SliderController');

    Route::resource('users', 'Admin\UserController');

    Route::get('/clear-cache', 'Admin\AdminBaseController@clearCache')->name('panel.clear.cache');

    Route::get('/logout', 'Admin\GuardController@logout')->name('panel.logout');
});


//Route::group(['middleware' => 'page-cache'], function () {

    Route::get('/sss', 'Site\PageController@faqs')
        ->name('sss');

    Route::get('/iletisim', 'Site\PageController@contact')
        ->name('contact');

//products
    Route::get('/etkinlikler', 'Site\EventController@events')
        ->name('events');

//product
    Route::get('/etkinlik/{slug}', 'Site\EventController@event')
        ->where('slug', '([A-Za-z0-9\-\/]+)')
        ->name('event');

//products
    Route::get('/urunler/{slug}', 'Site\ProductController@products')
        ->where('slug', '([A-Za-z0-9\-\/]+)')
        ->name('products');

//product
    Route::get('/urun/{category}/{slug}', 'Site\ProductController@product')
        ->where('category', '([A-Za-z0-9\-\/]+)')
        ->where('slug', '([A-Za-z0-9\-\/]+)')
        ->name('product');

//recipes
    Route::get('/tarifler', 'Site\RecipeController@recipes')
        ->where('slug', '([A-Za-z0-9\-\/]+)')
        ->name('recipes');

//recipe
    Route::get('/tarif/{slug}', 'Site\RecipeController@recipe')
        ->where('slug', '([A-Za-z0-9\-\/]+)')
        ->name('recipe');

//pages
    Route::get('{slug}', 'Site\PageController@page')
        ->where('slug', '([A-Za-z0-9\-\/]+)')
        ->name('page');

//home
    Route::get('/', [
        'as'   => 'home',
        'uses' => 'Site\PageController@index'
    ]);
//});

resources/views/admin/content/section/_list.blade.php
@extends('admin.layouts.main')
@section('content')
    @include('admin.parts.breadcrumb',['page'=> 'Sayfa Bölümleri'])
    <div class="m-content">
        <div class="m-portlet m-portlet--mobile">
            <div class="m-portlet__head">
                <div class="m-portlet__head-caption">
                    <div class="m-portlet__head-title">
                        <h3 class="m-portlet__head-text">
                            {{$sections[0]->page->name}} Listesi
                        </h3>
                    </div>
                </div>
            </div>
            <div class="m-portlet__body">
                <!--begin: Search Form -->
                <div class="m-form m-form--label-align-right m--margin-top-20 m--margin-bottom-30">
                    <div class="row align-items-center">
                        <div class="col-lg-8">
                            <div class="m-alert m-alert--icon m-alert--outline alert alert-primary" role="alert">
                                <div class="m-alert__icon">
                                    <i class="la la-info-circle"></i>
                                </div>
                                <div class="m-alert__text">
                                    Sürükle bırak ile sıralamayı değiştirebilirsiniz.
                                </div>
                            </div>
                        </div>
                        <div class="col-lg-4 m--align-right">
                            <a href="{{route('page.sections.create',['page'=>$sections[0]->page->route])}}"
                               class="btn btn-primary m-btn m-btn--custom m-btn--icon m-btn--air m-btn--pill">
												<span>
													<i class="la la-question-circle"></i>
													<span>
													{{$sections[0]->page->name}} İçin Yeni Bölüm Ekle
													</span>
												</span>
                            </a>
                            <div class="m-separator m-separator--dashed d-xl-none"></div>
                        </div>
                    </div>
                </div>

                <div class="row" id="m_sortable_portlets">
                    <div class="col-lg-12">
                        @foreach($sections as $section)
                            <div class="m-portlet m-portlet--mobile m-portlet--sortable" id="item-{{$section->id}}">
                                <div class="m-portlet__head">
                                    <div class="m-portlet__head-caption">
                                        <div class="m-portlet__head-title">
                                            <h3 class="m-portlet__head-text">
                                                @if($section->title)
                                                    {{$section->title}}
                                                @else
                                                    Son Bölüm
                                                @endif
                                            </h3>
                                        </div>
                                    </div>
                                    <div class="m-portlet__head-tools">
                                        <ul class="m-portlet__nav">
                                            <li class="m-portlet__nav-item">
                                                <a href="{{route('page.sections.edit', ['page'=>$section->page->route, 'id'=>$section->id])}}"
                                                   class="m-portlet__nav-link btn btn-secondary m-btn m-btn--icon m-btn--icon-only m-btn--pill">
                                                    <i class="la la-edit"></i>
                                                </a>
                                            </li>
                                            @if($section->deletable === 1)
                                                <li class="m-portlet__nav-item">
                                                    <a href="#" data-id="{{$section->id}}"
                                                       class="m-portlet__nav-link btn btn-secondary m-btn m-btn--icon m-btn--icon-only m-btn--pill del">
                                                        <i class="la la-trash"></i>
                                                    </a>
                                                </li>
                                            @endif
                                        </ul>
                                    </div>
                                </div>
                            </div>
                        @endforeach
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

@section('page_js')
    <!--begin::Page Vendors -->
    <script src="{{asset('assets/admin/assets/vendors/custom/jquery-ui/jquery-ui.bundle.js')}}"
            type="text/javascript"></script>
    <!--end::Page Vendors -->
    <script>

        $(function () {
            $('body').on('click', 'a.del', function (e) {
                e.preventDefault();
                var id = $(this).data('id');

                swal({
                    title: "Uyarı!",
                    text: "Silmek istediğinize emin misiniz?",
                    type: "warning",
                    showCancelButton: true,
                    confirmButtonColor: 'btn btn-danger',
                    confirmButtonText: "Evet",
                    cancelButtonText: "İptal"
                }).then(function (result) {
                    if (result.value) {
                        $.ajax({
                            url: '/admin-panel/page/{{$sections[0]->page->route}}/sections/' + id,
                            dataType: "json",
                            type: 'DELETE',
                            success: function (result) {
                                if (result.status)
                                    location.reload();
                            }
                        });
                    }
                });
            });

            $("#m_sortable_portlets").sortable({
                connectWith: ".m-portlet__head",
                items: ".m-portlet",
                opacity: 0.8,
                handle: '.m-portlet__head',
                coneHelperSize: true,
                placeholder: 'm-portlet--sortable-placeholder',
                forcePlaceholderSize: true,
                tolerance: "pointer",
                helper: "clone",
                cancel: ".m-portlet--sortable-empty", // cancel dragging if portlet is in fullscreen mode
                revert: 250, // animation in milliseconds
                update: function (b, c) {
                    if (c.item.prev().hasClass("m-portlet--sortable-empty")) {
                        c.item.prev().before(c.item);
                    }

                    var data = $('#m_sortable_portlets').sortable('serialize')+'&page={{$sections[0]->page->route}}';

                    $.ajax({
                        data: data,
                        dataType: "json",
                        type: 'POST',
                        url: '{{ route('sections.sort') }}',
                        success: function (result) {
                            if (result.status) {
                                swal({
                                    title: 'Bilgi',
                                    text: 'İşleminiz gerçekleştirildi',
                                    timer: 2000,
                                    type: 'success',
                                    showConfirmButton: false
                                });
                            }

                        }
                    });
                }
            });

        });
    </script>
@endsection

resources/views/admin/content/section/create.blade.php
@extends('admin.layouts.main')
@section('content')
    <!-- BEGIN: Subheader -->
    @include('admin.parts.breadcrumb',['page'=> 'Bölüm Bilgileri'])
    <div class="m-content">
        <!--Begin::Section-->
        <div class="row">
            <div class="col-lg-12">
                <!--begin::Portlet-->
                <div class="m-portlet">
                    <div class="m-portlet__head">
                        <div class="m-portlet__head-caption">
                            <div class="m-portlet__head-title">
												<span class="m-portlet__head-icon m--hide">
													<i class="la la-gear"></i>
												</span>
                                <h3 class="m-portlet__head-text">
                                    Bilgiler
                                </h3>
                            </div>
                        </div>
                    </div>
                    {!! Form::open(['route' => ['page.sections.store', 'page'=>$page ], 'class'=>'m-form', 'method'=>'PUT', 'files' => true]) !!}
                    <div class="m-portlet__body">
                        @if ($errors->any())
                            <div class="alert alert-danger">
                                <ul>
                                    @foreach ($errors->all() as $error)
                                        <li>{{ $error }}</li>
                                    @endforeach
                                </ul>
                            </div>
                        @endif
                        <div class="form-group m-form__group col-lg-9">
                            {!! Form::label('route', 'Route (Rota - Slug) :'); !!}
                            {!! Form::text('route', null, ['class' => 'form-control m-input']); !!}
                        </div>

                        <div class="form-group m-form__group col-lg-3">
                            {!! Form::label('type', 'Görsel Tipi :'); !!}
                            {!! Form::select('type', [ '0' => 'Ana Sayfa', '1' => 'Kısa Görsel', '2' => 'Uzun Görsel', '3' => 'Sayfa Footer Görsel'], null, ['class' => 'form-control m-input']); !!}
                        </div>
                        <div class="form-group m-form__group col-lg-3">
                            {!! Form::label('image_direction', 'Görsel Yeri :'); !!}
                            {!! Form::select('image_direction', ['0'=> 'Sayfa Footer', '1' => 'Solda', '2' => 'Sağda'],null, ['class' => 'form-control m-input']); !!}
                        </div>
                        <div class="form-group m-form__group col-lg-9">
                            {!! Form::label('image', 'Görsel :'); !!}
                            {!! Form::file('image'); !!}
                        </div>
                        <div class="form-group m-form__group col-lg-9">
                            {!! Form::label('title_optional', 'Footer Bölüm Üst Yazı :'); !!}
                            {!! Form::textarea('title_optional',null, ['class' => 'form-control m-input']); !!}
                        </div>
                        <div class="form-group m-form__group col-lg-9">
                            {!! Form::label('title', 'Bölüm Başlık :'); !!}
                            {!! Form::textarea('title',null, ['class' => 'form-control m-input']); !!}
                        </div>
                        <div class="form-group m-form__group col-lg-9">
                            {!! Form::label('content', 'Bölüm İçerik :'); !!}
                            {!! Form::textarea('content',null, ['class' => 'form-control m-input summernote']); !!}
                        </div>
                        <div class="form-group m-form__group col-lg-3">
                            {!! Form::label('active', 'Durum :'); !!}
                            {!! Form::select('active', ['0' => 'Pasif', '1' => 'Aktif'],null, ['class' => 'form-control m-input']); !!}
                        </div>
                    </div>
                    <div class="m-portlet__foot m-portlet__foot--fit">
                        <div class="m-form__actions m-form__actions">
                            <button class="btn btn-primary">
                                {!! Form::submit('Kaydet', ['class'=>'btn btn-primary']) !!}
                            </button>
                        </div>
                    </div>
                    {!! Form::close() !!}
                </div>
                <!--end::Portlet-->
            </div>
        </div>
        <!--End::Section-->
    </div>
@endsection
@section('page_js')
    <!--begin::Page Resources -->
    <script src="{{asset('assets/admin/assets/demo/default/custom/components/forms/widgets/summernote.js')}}"
            type="text/javascript"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/summernote/0.8.10/lang/summernote-tr-TR.min.js"
            type="text/javascript"></script>
    <!--end::Page Resources -->
@endsection

resources/views/admin/content/section/edit.blade.php
@extends('admin.layouts.main')
@section('content')
    <!-- BEGIN: Subheader -->
    @include('admin.parts.breadcrumb',['page'=> 'Bölüm Bilgileri'])
    <div class="m-content">
        <!--Begin::Section-->
        <div class="row">
            <div class="col-lg-12">
                <!--begin::Portlet-->
                <div class="m-portlet">
                    <div class="m-portlet__head">
                        <div class="m-portlet__head-caption">
                            <div class="m-portlet__head-title">
												<span class="m-portlet__head-icon m--hide">
													<i class="la la-gear"></i>
												</span>
                                <h3 class="m-portlet__head-text">
                                    Bilgiler
                                </h3>
                            </div>
                        </div>
                    </div>
                    {!! Form::model($section, ['route' => ['page.sections.update', 'page'=>$page , 'id'=>$section->id], 'class'=>'m-form', 'method'=>'PUT', 'files' => true]) !!}
                    <div class="m-portlet__body">
                        @if ($errors->any())
                            <div class="alert alert-danger">
                                <ul>
                                    @foreach ($errors->all() as $error)
                                        <li>{{ $error }}</li>
                                    @endforeach
                                </ul>
                            </div>
                        @endif
                        @if($section->deletable === 1)
                            <div class="form-group m-form__group col-lg-9">
                                {!! Form::label('route', 'Route (Rota - Slug) :'); !!}
                                @if($section->route)
                                    {!! Form::text('route', null, ['class' => 'form-control m-input']); !!}
                                @else
                                    {!! Form::text('route', null, ['class' => 'form-control m-input', 'placeholder'=> 'Herhangi bir içeriğe yönlendirme bulunmamaktadır!']); !!}
                                @endif
                            </div>
                        @endif
                        <div class="form-group m-form__group col-lg-3">
                            {!! Form::label('type', 'Görsel Tipi :'); !!}
                            {!! Form::select('type', [ '0' => 'Ana Sayfa', '1' => 'Kısa Görsel', '2' => 'Uzun Görsel', '3' => 'Sayfa Footer Görsel'], $section->type, ['class' => 'form-control m-input']); !!}
                        </div>
                        <div class="form-group m-form__group col-lg-3">
                            {!! Form::label('image_direction', 'Görsel Yeri :'); !!}
                            {!! Form::select('image_direction', ['0'=> 'Sayfa Footer', '1' => 'Solda', '2' => 'Sağda'],$section->image_direction, ['class' => 'form-control m-input']); !!}
                        </div>
                        <div class="form-group m-form__group col-lg-9">
                            {!! Form::label('image', 'Görsel :'); !!}
                            @if($section->image)
                                <div class="form-group m-form__group col-lg-9" style="padding-left: 0 !important;">
                                    <img src="{{$section->image}}" style="width: 600px"/>
                                </div>
                            @endif
                            {!! Form::file('image'); !!}
                        </div>
                        <div class="form-group m-form__group col-lg-9">
                            {!! Form::label('title_optional', 'Footer Bölüm Üst Yazı :'); !!}
                            {!! Form::textarea('title_optional',null, ['class' => 'form-control m-input']); !!}
                        </div>
                        <div class="form-group m-form__group col-lg-9">
                            {!! Form::label('title', 'Bölüm Başlık :'); !!}
                            {!! Form::textarea('title',null, ['class' => 'form-control m-input']); !!}
                        </div>
                        <div class="form-group m-form__group col-lg-9">
                            {!! Form::label('content', 'Bölüm İçerik :'); !!}
                            {!! Form::textarea('content',null, ['class' => 'form-control m-input summernote']); !!}
                        </div>
                        <div class="form-group m-form__group col-lg-3">
                            {!! Form::label('active', 'Durum :'); !!}
                            {!! Form::select('active', ['0' => 'Pasif', '1' => 'Aktif'],$section->active, ['class' => 'form-control m-input']); !!}
                        </div>
                    </div>
                    <div class="m-portlet__foot m-portlet__foot--fit">
                        <div class="m-form__actions m-form__actions">
                            <button class="btn btn-primary">
                                {!! Form::submit('Kaydet', ['class'=>'btn btn-primary']) !!}
                            </button>
                        </div>
                    </div>
                    {!! Form::close() !!}
                </div>
                <!--end::Portlet-->
            </div>
        </div>
        <!--End::Section-->
    </div>
@endsection
@section('page_js')
    <!--begin::Page Resources -->
    <script src="{{asset('assets/admin/assets/demo/default/custom/components/forms/widgets/summernote.js')}}"
            type="text/javascript"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/summernote/0.8.10/lang/summernote-tr-TR.min.js"
            type="text/javascript"></script>
    <!--end::Page Resources -->
@endsection

resources/views/admin/content/section/list.blade.php
@extends('admin.layouts.main')
@section('content')
    @include('admin.parts.breadcrumb',['page'=> 'Sayfa Bölümleri'])
    <div class="m-content">
        <div class="m-portlet m-portlet--mobile">
            <div class="m-portlet__head">
                <div class="m-portlet__head-caption">
                    <div class="m-portlet__head-title">
                        <h3 class="m-portlet__head-text">
                            {{$sections[0]->page->name}} Listesi
                        </h3>
                    </div>
                </div>
            </div>
            <div class="m-portlet__body">
                <!--begin: Search Form -->
                <div class="m-form m-form--label-align-right m--margin-top-20 m--margin-bottom-30">
                    <div class="row align-items-center">
                        <div class="col-lg-12 m--align-right">
                            <a href="{{route('page.sections.create',['page'=>$sections[0]->page->route])}}"
                               class="btn btn-primary m-btn m-btn--custom m-btn--icon m-btn--air m-btn--pill">
												<span>
													<i class="la la-plus-circle"></i>
													<span>
													{{$sections[0]->page->name}} İçin Yeni Bölüm Ekle
													</span>
												</span>
                            </a>
                            <div class="m-separator m-separator--dashed d-xl-none"></div>
                        </div>
                    </div>
                </div>

                <div class="m-portlet">
                    <div class="m-portlet__body">
                        <!--begin::Section-->
                        <div class="m-section">
                            <div class="m-section__content">
                                <table class="table table-striped m-table">
                                    <thead>
                                    <tr>
                                        <th>
                                            Başlık
                                        </th>
                                        <th>
                                            Durum
                                        </th>
                                        <th>
                                            İşlemler
                                        </th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                    @foreach($sections as $section)
                                        <tr>
                                            <td style="width: 80%">
                                                @if($section->title)
                                                    {{$section->title}}
                                                @else
                                                    Son Bölüm
                                                @endif
                                            </td>
                                            <td>
                                                @if($section->active === 1)
                                                    <span class="m-badge  m-badge--success m-badge--wide">Aktif</span>
                                                @else
                                                    <span class="m-badge  m-badge--danger m-badge--wide">Pasif</span>
                                                @endif
                                            </td>
                                            <td style="width: 20%">
                                                <a href="{{route('page.sections.edit', ['page'=>$section->page->route, 'id'=>$section->id])}}"
                                                   class="m-portlet__nav-link btn m-btn m-btn--hover-accent m-btn--icon m-btn--icon-only m-btn--pill"
                                                   title="Düzenle">
                                                    <i class="la la-edit"></i>
                                                </a>
                                                @if($section->deletable === 1)
                                                    <a href="#" data-id="{{$section->id}}"
                                                       class="m-portlet__nav-link btn m-btn m-btn--hover-danger m-btn--icon m-btn--icon-only m-btn--pill del"
                                                       title="Sil">
                                                        <i class="la la-trash"></i>
                                                    </a>
                                                @endif
                                            </td>
                                        </tr>
                                    @endforeach
                                    </tbody>
                                </table>
                            </div>
                        </div>
                        <!--end::Section-->
                    </div>
                    <!--end::Form-->
                </div>

            </div>
        </div>
    </div>
@endsection

@section('page_js')

    <script>

        $(function () {
            $('body').on('click', 'a.del', function (e) {
                e.preventDefault();
                var id = $(this).data('id');

                swal({
                    title: "Uyarı!",
                    text: "Silmek istediğinize emin misiniz?",
                    type: "warning",
                    showCancelButton: true,
                    confirmButtonColor: 'btn btn-danger',
                    confirmButtonText: "Evet",
                    cancelButtonText: "İptal"
                }).then(function (result) {
                    if (result.value) {
                        $.ajax({
                            url: '{{route('pages.index')}}/' + id,
                            dataType: "json",
                            type: 'DELETE',
                            success: function (result) {
                                if (result.status)
                                    location.reload();
                            }
                        });
                    }
                });
            });
        });
    </script>
@endsection