routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/admin', 'Admin\GuardController@index')->name('panel.index');
Route::post('/check', 'Admin\GuardController@check')->name('login.check');

Route::group(['prefix' => 'admin-panel'], function () {
    Route::get('/dashboard', 'Admin\PanelController@index')->name('panel.welcome');

    Route::get('events/get', 'Admin\EventController@get')->name('events.get');
    Route::post('events/upload', 'Admin\EventController@upload')->name('events.upload');
    Route::post('events/delete', 'Admin\EventController@imageDelete')->name('event.image.delete');
    Route::resource('events', 'Admin\EventController');

    Route::post('faqs/sort', 'Admin\FaqController@sort')->name('faqs.sort');
    Route::resource('faqs', 'Admin\FaqController');

    Route::post('elements/sort', 'Admin\MenuElementController@sort')->name('elements.sort');
    Route::resource('menu.elements', 'Admin\MenuElementController');

    Route::resource('menus', 'Admin\MenuController');

    Route::resource('pages', 'Admin\PageController');

    Route::post('sections/sort', 'Admin\PageSectionController@sort')->name('sections.sort');
    Route::resource('page.sections', 'Admin\PageSectionController');

    Route::get('product-categories/get', 'Admin\CategoryController@get')->name('product-categories.get');
    Route::resource('product-categories', 'Admin\CategoryController');

    Route::post('products/sort', 'Admin\ProductController@sort')->name('products.sort');
    Route::get('products/get', 'Admin\ProductController@get')->name('products.get');
    Route::resource('products', 'Admin\ProductController');

    Route::get('recipes/get', 'Admin\RecipeController@get')->name('recipes.get');
    Route::resource('recipes', 'Admin\RecipeController');

    Route::resource('site-settings', 'Admin\SettingController');

    Route::post('slides/sort', 'Admin\SliderController@sort')->name('slides.sort');
    Route::resource('slides', 'Admin\SliderController');

    Route::resource('users', 'Admin\UserController');

    Route::get('/clear-cache', 'Admin\AdminBaseController@clearCache')->name('panel.clear.cache');

    Route::get('/logout', 'Admin\GuardController@logout')->name('panel.logout');
});


//Route::group(['middleware' => 'page-cache'], function () {

    Route::get('/sss', 'Site\PageController@faqs')
        ->name('sss');

    Route::get('/iletisim', 'Site\PageController@contact')
        ->name('contact');

//products
    Route::get('/etkinlikler', 'Site\EventController@events')
        ->name('events');

//product
    Route::get('/etkinlik/{slug}', 'Site\EventController@event')
        ->where('slug', '([A-Za-z0-9\-\/]+)')
        ->name('event');

//products
    Route::get('/urunler/{slug}', 'Site\ProductController@products')
        ->where('slug', '([A-Za-z0-9\-\/]+)')
        ->name('products');

//product
    Route::get('/urun/{category}/{slug}', 'Site\ProductController@product')
        ->where('category', '([A-Za-z0-9\-\/]+)')
        ->where('slug', '([A-Za-z0-9\-\/]+)')
        ->name('product');

//recipes
    Route::get('/tarifler', 'Site\RecipeController@recipes')
        ->where('slug', '([A-Za-z0-9\-\/]+)')
        ->name('recipes');

//recipe
    Route::get('/tarif/{slug}', 'Site\RecipeController@recipe')
        ->where('slug', '([A-Za-z0-9\-\/]+)')
        ->name('recipe');

//pages
    Route::get('{slug}', 'Site\PageController@page')
        ->where('slug', '([A-Za-z0-9\-\/]+)')
        ->name('page');

//home
    Route::get('/', [
        'as'   => 'home',
        'uses' => 'Site\PageController@index'
    ]);
//});

app/Models/User.php
<?php

/**
 * Created by Reliese Model.
 * Date: Thu, 12 Apr 2018 13:04:53 +0000.
 */

namespace App\Models;
use Illuminate\Contracts\Auth\Authenticatable;
use Illuminate\Auth\Authenticatable as AuthenticableTrait;

use Reliese\Database\Eloquent\Model as Eloquent;

/**
 * Class User
 * 
 * @property int $id
 * @property string $name
 * @property string $username
 * @property string $password
 * @property string $remember_token
 * @property \Carbon\Carbon $created_at
 * @property \Carbon\Carbon $updated_at
 *
 * @package App\Models
 */
class User  extends Eloquent implements Authenticatable
{
    use AuthenticableTrait;

	protected $hidden = [
		'password',
		'remember_token'
	];

	protected $fillable = [
		'name',
		'username',
		'password'
	];
}

app/Http/Controllers/Admin/UserController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Models\User;
use Illuminate\Http\Request;

class UserController extends AdminBaseController
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $users = User::all();
        return view('admin.content.user.list', compact('users'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.content.user.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'name'     => 'required|max:255',
            'username' => 'required|max:255',
            'password' => 'required|max:255'
        ]);

        $check = User::where('username', $request->username)->first();

        if ($check !== null) {
            \Session::flash('error', 'Bu kullanıcı adı ile daha önce bir kullanıcı yaratılmış');

            return redirect()->route('users.index');
        }

        $user           = new User();
        $user->name     = $request->name;
        $user->username = $request->username;
        $user->password = \Hash::make($request->password);

        $user->save();

        \Session::flash('success', 'İşleminiz gerçekleştirildi');

        return redirect()->route('users.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $user = User::find($id);

        if ($user === null) {
            \Session::flash('error', 'Kayıt bulunamadı');
            return redirect()->route('users.index');
        }

        return view('admin.content.user.edit', compact('user'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->validate($request, [
            'name'     => 'required|max:255',
            'username' => 'required|max:255'
        ]);

        $user           = User::find($id);
        $user->name     = $request->name;
        $user->username = $request->username;
        if ($request->password) {
            $user->password = \Hash::make($request->password);
        }

        $user->save();

        \Session::flash('success', 'İşleminiz gerçekleştirildi');

        return redirect()->route('users.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $user = User::find($id);

        if ($user === null) {
            \Session::flash('error', 'Kayıt bulunamadı');
            return ['status' => false];
        }

        $user->delete();

        \Session::flash('success', 'İşleminiz gerçekleştirildi');

        return ['status' => true];
    }
}

resources/views/admin/content/user/create.blade.php
@extends('admin.layouts.main')
@section('content')
    <!-- BEGIN: Subheader -->
    @include('admin.parts.breadcrumb',['page'=> 'Panel Kullanıcıları'])
    <div class="m-content">
        <!--Begin::Section-->
        <div class="row">
            <div class="col-lg-12">
                <!--begin::Portlet-->
                <div class="m-portlet">
                    <div class="m-portlet__head">
                        <div class="m-portlet__head-caption">
                            <div class="m-portlet__head-title">
												<span class="m-portlet__head-icon m--hide">
													<i class="la la-user"></i>
												</span>
                                <h3 class="m-portlet__head-text">
                                    Kullanıcı Bilgiler
                                </h3>
                            </div>
                        </div>
                    </div>
                    {!! Form::open(['route' => 'users.store', 'class'=>'m-form']) !!}
                    <div class="m-portlet__body">
                        @if ($errors->any())
                            <div class="alert alert-danger">
                                <ul>
                                    @foreach ($errors->all() as $error)
                                        <li>{{ $error }}</li>
                                    @endforeach
                                </ul>
                            </div>
                        @endif
                        <div class="form-group m-form__group col-lg-4">
                            {!! Form::label('name', 'Adı :'); !!}
                            {!! Form::text('name', null, ['class' => 'form-control m-input']); !!}
                        </div>
                        <div class="form-group m-form__group col-lg-4">
                            {!! Form::label('username', 'Kullanıcı Adı :'); !!}
                            {!! Form::text('username', null, ['class' => 'form-control m-input']); !!}
                        </div>
                        <div class="form-group m-form__group col-lg-4">
                            {!! Form::label('password', 'Şifre :'); !!}
                            {!! Form::password('password', ['class' => 'form-control m-input']);!!}
                        </div>
                    </div>
                    <div class="m-portlet__foot m-portlet__foot--fit">
                        <div class="m-form__actions m-form__actions">
                            <button class="btn btn-primary">
                                {!! Form::submit('Kaydet', ['class'=>'btn btn-primary']) !!}
                            </button>
                        </div>
                    </div>
                    {!! Form::close() !!}
                </div>
                <!--end::Portlet-->
            </div>
        </div>
        <!--End::Section-->
    </div>
@endsection
@section('page_js')
    <!--begin::Page Resources -->
    <script src="{{asset('assets/admin/assets/demo/default/custom/components/forms/widgets/summernote.js')}}"
            type="text/javascript"></script>
    <!--end::Page Resources -->
@endsection

resources/views/admin/content/user/edit.blade.php
@extends('admin.layouts.main')
@section('content')
    <!-- BEGIN: Subheader -->
    @include('admin.parts.breadcrumb',['page'=> 'Etkinlikler'])
    <div class="m-content">
        <!--Begin::Section-->
        <div class="row">
            <div class="col-lg-12">
                <!--begin::Portlet-->
                <div class="m-portlet">
                    <div class="m-portlet__head">
                        <div class="m-portlet__head-caption">
                            <div class="m-portlet__head-title">
												<span class="m-portlet__head-icon m--hide">
													<i class="la la-gear"></i>
												</span>
                                <h3 class="m-portlet__head-text">
                                    Etkinlik Bilgiler
                                </h3>
                            </div>
                        </div>
                    </div>
                    {!! Form::model($user,['route' => ['users.update', $user->id], 'class'=>'m-form', 'method'=>'PUT']) !!}
                    <div class="m-portlet__body">
                        @if ($errors->any())
                            <div class="alert alert-danger">
                                <ul>
                                    @foreach ($errors->all() as $error)
                                        <li>{{ $error }}</li>
                                    @endforeach
                                </ul>
                            </div>
                        @endif
                        <div class="form-group m-form__group col-lg-4">
                            {!! Form::label('name', 'Adı :'); !!}
                            {!! Form::text('name', null, ['class' => 'form-control m-input']); !!}
                        </div>
                        <div class="form-group m-form__group col-lg-4">
                            {!! Form::label('username', 'Kullanıcı Adı :'); !!}
                            {!! Form::text('username', null, ['class' => 'form-control m-input']); !!}
                        </div>
                        <div class="form-group m-form__group col-lg-4">
                            {!! Form::label('password', 'Şifre :'); !!}
                            {!! Form::password('password', ['class' => 'form-control m-input']);!!}
                        </div>
                    </div>
                    <div class="m-portlet__foot m-portlet__foot--fit">
                        <div class="m-form__actions m-form__actions">
                            <button class="btn btn-primary">
                                {!! Form::submit('Kaydet', ['class'=>'btn btn-primary']) !!}
                            </button>
                        </div>
                    </div>
                    {!! Form::close() !!}
                </div>
                <!--end::Portlet-->
            </div>
        </div>
        <!--End::Section-->
    </div>
@endsection
@section('page_js')
    <!--begin::Page Resources -->
    <script src="{{asset('assets/admin/assets/demo/default/custom/components/forms/widgets/summernote.js')}}" type="text/javascript"></script>
    <!--end::Page Resources -->
@endsection

resources/views/admin/content/user/list.blade.php
@extends('admin.layouts.main')
@section('content')
    @include('admin.parts.breadcrumb',['page'=> 'Panel Kullanıcıları'])
    <div class="m-content">
        <div class="m-portlet m-portlet--mobile">
            <div class="m-portlet__head">
                <div class="m-portlet__head-caption">
                    <div class="m-portlet__head-title">
                        <h3 class="m-portlet__head-text">
                            Panel Kullanıcı Listesi
                        </h3>
                    </div>
                </div>
            </div>
            <div class="m-portlet__body">
                <!--begin: Search Form -->
                <div class="m-form m-form--label-align-right m--margin-top-20 m--margin-bottom-30">
                    <div class="row align-items-center">
                        <div class="col-lg-12 m--align-right">
                            <a href="{{route('users.create')}}"
                               class="btn btn-primary m-btn m-btn--custom m-btn--icon m-btn--air m-btn--pill">
												<span>
													<i class="la la-plus-circle"></i>
													<span>
													Yeni Ekle
													</span>
												</span>
                            </a>
                            <div class="m-separator m-separator--dashed d-xl-none"></div>
                        </div>
                    </div>
                </div>

                <div class="m-portlet">
                    <div class="m-portlet__body">
                        <!--begin::Section-->
                        <div class="m-section">
                            <div class="m-section__content">
                                <table class="table table-striped m-table">
                                    <thead>
                                    <tr>
                                        <th>
                                            Adı
                                        </th>
                                        <th>
                                            Kullanıcı Adı
                                        </th>
                                        <th>
                                            İşlemler
                                        </th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                    @foreach($users as $user)
                                        <tr>
                                            <td>
                                                {{$user->name}}
                                            </td>
                                            <td>
                                                {{$user->username}}
                                            </td>
                                            <td style="width: 20%">
                                                <a href="{{route('users.edit', ['id'=>$user->id])}}"
                                                   class="m-portlet__nav-link btn m-btn m-btn--hover-accent m-btn--icon m-btn--icon-only m-btn--pill"
                                                   title="Düzenle">
                                                    <i class="la la-edit"></i>
                                                </a>

                                                <a href="#" data-id="{{$user->id}}"
                                                   class="m-portlet__nav-link btn m-btn m-btn--hover-danger m-btn--icon m-btn--icon-only m-btn--pill del"
                                                   title="Sil">
                                                    <i class="la la-trash"></i>
                                                </a>

                                            </td>
                                        </tr>
                                    @endforeach
                                    </tbody>
                                </table>
                            </div>
                        </div>
                        <!--end::Section-->
                    </div>
                    <!--end::Form-->
                </div>

            </div>
        </div>
    </div>
@endsection

@section('page_js')

    <script>

        $(function () {
            $('body').on('click', 'a.del', function (e) {
                e.preventDefault();
                var id = $(this).data('id');

                swal({
                    title: "Uyarı!",
                    text: "Silmek istediğinize emin misiniz?",
                    type: "warning",
                    showCancelButton: true,
                    confirmButtonColor: 'btn btn-danger',
                    confirmButtonText: "Evet",
                    cancelButtonText: "İptal"
                }).then(function (result) {
                    if (result.value) {
                        $.ajax({
                            url: '{{route('users.index')}}/' + id,
                            dataType: "json",
                            type: 'DELETE',
                            success: function (result) {
                                if (result.status)
                                    location.reload();
                            }
                        });
                    }
                });
            });
        });
    </script>
@endsection